
DROP TABLE IF EXISTS computers CASCADE;
DROP TABLE IF EXISTS applications;

CREATE TABLE computers (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  brand TEXT NOT NULL,
  model TEXT,
  url TEXT NOT NULL
);
CREATE TABLE applications (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  computer_id BIGINT REFERENCES computers(id)
);
